[tool.poetry]
name = "lewagon-project"
version = "0.1.0"
description = ""
authors = ["yannis bouhamou <yannis.bouhamou@hotmail.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
